# Configuración de SonarQube - Módulo de Banca Electrónica
# Este archivo define los parámetros del proyecto para el
# análisis estático de seguridad (SAST) con SonarQube.

# --- Identificación del Proyecto ---
sonar.projectKey=Renato6GS_admin-website-sonarqube
sonar.projectName=Mensajes asícronos
sonar.projectVersion=1.0.0
sonar.organization=renato6gs
