server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # El servidor no se registra a sí mismo ni consulta otro registro
    register-with-eureka: false
    fetch-registry: false
